
SELECT * FROM customer limit 10


-- RUNNING QUERIES

-- Q1 Which are the top 5 products with the highest average review rating?



SELECT item_purchased AS products,
AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;



-- Q2 Which 5 products have the highest percentage of purchases with disocunts applied?


SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 2nd method

SELECT 
item_purchased AS products,
COUNT (*) AS total_purchases,
SUM (CASE  WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,

ROUND

(100.0 * SUM (CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2 ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q3 What is the total revenue generated by Male vs Female customers?


SELECT gender,
SUM(purchase_amount) AS total_revenue FROM
customer
GROUP BY gender;


-- Q4 What are the top 3 most purchased products within each category?


WITH items_count AS(
SELECT 
category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM items_count
WHERE item_rank <= 3;



-- Q5 Which customers used a discount but still spent more than the average purchase amount?

SELECT 
customer_id,
item_purchased,
purchase_amount,
discount_applied
FROM
customer
WHERE discount_applied = 'Yes' 
AND
purchase_amount > (SELECT AVG(purchase_amount) FROM customer);



-- Q6 segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment


WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returining'
	ELSE 'lOYAL'
    END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) AS "number_of_customers"
FROM customer_type
GROUP BY customer_segment;



-- Q7 Compare the average purchase amounts between standard & express shipping method?

SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM
customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;



-- Q8 Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non-subscriber.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND (AVG(purchase_amount),2 ) AS average_spend,
ROUND (SUM(purchase_amount),2 ) AS total_revenue
FROM
customer
GROUP BY subscription_status
ORDER BY average_spend, total_revenue DESC;


-- Q9 What is revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

